base_config:
  - egs/egs_bases/tts/vocoder/base.yaml
  - egs/datasets/audio/lj/base_mel2wav.yaml
  - ./base.yaml

raw_data_dir: 'data/raw/LJSpeech-1.1'
processed_data_dir: 'data/processed/LJSpeech'
binary_data_dir: 'data/binary/LJSpeech'
