base_config:
  - egs/egs_bases/tts/vocoder/base.yaml
  - egs/datasets/audio/vctk/base_mel2wav.yaml
  - ./base.yaml

raw_data_dir: 'data/raw/VCTK'
processed_data_dir: 'data/processed/VCTK'
binary_data_dir: 'data/binary/VCTK'