base_config:
  - egs/egs_bases/tts/vocoder/base.yaml
  - egs/datasets/audio/libritts/base_mel2wav.yaml
  - ./base.yaml

raw_data_dir: 'data/raw/LibriTTS'
processed_data_dir: 'data/processed/LibriTTS'
binary_data_dir: 'data/binary/LibriTTS'